### ISSUE TITLE
[Router] Implement type-safe router

### ISSUE THREAD

**Issue by danneu** [danneu/kog#3]
The API could look something like this:

``` kotlin
Router {
    get("/users/:id", fun(id: Int): Handler = { req ->
        Response().text("User $id")
    })
}
```

### TODO:

- [x] Middleware tests
- [x] Figure out a good `group("/prefix")` API.
- [x] Support websockets
    - Could map SafeRouter patterns into jetty context paths with wildcards: http://stackoverflow.com/questions/4798120/is-it-possible-to-use-regular-expression-for-jettys-servlet-mapping
- [x] Build router using reflection once so that the router isn't using reflection (slow) during dispatch. Right now it naively uses reflection on every request when instead it should compile a mapping at init. (Even though I improved it and checked the box, more work could be done)
- [x] Consider compiling one regex that maps requests to handlers.

**Comment by danneu** [comment]
Got the gist of it working: https://github.com/danneu/kog/commit/143f929e22cd1c998bb375ba530f2de476c5fdfd

Though isn't yet feature-full.

**Comment by danneu** [comment]
Deleted the old `Router.kt` and renamed `SafeRouter.kt` to `Router.kt`.
